// <auto-generated />
using System;
using DeliverlyCore.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliverlyCore.Infra.Migrations
{
    [DbContext(typeof(DeliverlyDbContext))]
    [Migration("20260310132737_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliverlyCore.Pricing.Domain.Entities.TariffTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("tariff", (string)null);
                });

            modelBuilder.Entity("DeliverlyCore.Pricing.Domain.Entities.TariffTable", b =>
                {
                    b.OwnsOne("DeliverlyCore.Pricing.Domain.ValueObjects.ZipCode", "DestinationPrefix", b1 =>
                        {
                            b1.Property<Guid>("TariffTableId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("destination_prefix");

                            b1.HasKey("TariffTableId");

                            b1.ToTable("tariff");

                            b1.WithOwner()
                                .HasForeignKey("TariffTableId");
                        });

                    b.OwnsOne("DeliverlyCore.Pricing.Domain.ValueObjects.Weight", "MaxWeight", b1 =>
                        {
                            b1.Property<Guid>("TariffTableId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("max_weight");

                            b1.HasKey("TariffTableId");

                            b1.ToTable("tariff");

                            b1.WithOwner()
                                .HasForeignKey("TariffTableId");
                        });

                    b.OwnsOne("DeliverlyCore.Pricing.Domain.ValueObjects.Weight", "MinWeight", b1 =>
                        {
                            b1.Property<Guid>("TariffTableId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("min_weight");

                            b1.HasKey("TariffTableId");

                            b1.ToTable("tariff");

                            b1.WithOwner()
                                .HasForeignKey("TariffTableId");
                        });

                    b.OwnsOne("DeliverlyCore.Pricing.Domain.ValueObjects.ZipCode", "OriginPrefix", b1 =>
                        {
                            b1.Property<Guid>("TariffTableId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("origin_prefix");

                            b1.HasKey("TariffTableId");

                            b1.ToTable("tariff");

                            b1.WithOwner()
                                .HasForeignKey("TariffTableId");
                        });

                    b.OwnsOne("DeliverlyCore.Pricing.Domain.ValueObjects.Money", "BaseValue", b1 =>
                        {
                            b1.Property<Guid>("TariffTableId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("base_value_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base_value_currency");

                            b1.HasKey("TariffTableId");

                            b1.ToTable("tariff");

                            b1.WithOwner()
                                .HasForeignKey("TariffTableId");
                        });

                    b.Navigation("BaseValue")
                        .IsRequired();

                    b.Navigation("DestinationPrefix")
                        .IsRequired();

                    b.Navigation("MaxWeight")
                        .IsRequired();

                    b.Navigation("MinWeight")
                        .IsRequired();

                    b.Navigation("OriginPrefix")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
